//! Init scaffold helpers — port of `src/init/scaffold.mjs`.

use crate::error::SlopError;
use serde_json::{json, Value};
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

pub const DEPCRUISE_STARTER: &str = r"// generated by slopgate init — universal rules; add project layer rules here.
module.exports = {
  forbidden: [
    { name: 'no-circular', severity: 'error', from: {}, to: { circular: true } },
    { name: 'no-orphans', severity: 'warn', from: { orphan: true, pathNot: ['\\.d\\.ts$'] }, to: {} },
  ],
  options: { doNotFollow: { path: 'node_modules' }, tsPreCompilationDeps: true },
};
";

/// What happened when merging `.claude/settings.json`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SettingsAction {
    Created,
    Merged,
    AlreadyPresent,
    InvalidJson,
}

impl SettingsAction {
    pub fn as_str(self) -> &'static str {
        match self {
            SettingsAction::Created => "created",
            SettingsAction::Merged => "merged",
            SettingsAction::AlreadyPresent => "already-present",
            SettingsAction::InvalidJson => "invalid-json",
        }
    }
}

fn hook_paths(engine_root: &Path) -> (String, String, String) {
    let commit = engine_root.join("hooks/commit-hook.sh");
    let edit = engine_root.join("hooks/edit-hook.sh");
    let session = engine_root.join("hooks/session-start.sh");
    (
        commit.to_string_lossy().into_owned(),
        edit.to_string_lossy().into_owned(),
        session.to_string_lossy().into_owned(),
    )
}

fn json_array(values: &[String]) -> String {
    let inner: Vec<String> = values
        .iter()
        .map(|v| format!("\"{}\"", v.replace('\\', "\\\\").replace('"', "\\\"")))
        .collect();
    format!("[{}]", inner.join(", "))
}

/// Format native `.slopgate/config.toml` — 1:1 fields with JS `formatConfig` output.
pub fn format_config_toml(detected: &DetectedConfig) -> String {
    let mut out = String::new();
    out.push_str(&format!("roots = {}\n", json_array(&detected.roots)));
    out.push_str(&format!("exts = {}\n", json_array(&detected.exts)));
    out.push_str(&format!("skipDirs = {}\n", json_array(&detected.skip_dirs)));
    out.push_str("baseline = [\"no-stubs\", \"ts-suppress\", \"as-any\"]\n");
    out.push_str("rules = []\n");
    out.push_str("astRules = \"./rules/ast\"\n");
    out.push_str("astDisable = []\n");
    out.push_str("suppressions = \"./suppressions.json\"\n");
    out.push_str("fixtures = \"./fixtures\"\n");

    if let Value::Object(checkers) = &detected.checkers {
        let mut names: Vec<&String> = checkers.keys().collect();
        names.sort();
        for name in names {
            match checkers.get(name) {
                Some(Value::Bool(true)) => {
                    out.push_str(&format!("\n[checkers.{name}]\n"));
                }
                Some(Value::Object(fields)) => {
                    out.push_str(&format!("\n[checkers.{name}]\n"));
                    let mut keys: Vec<&String> = fields.keys().collect();
                    keys.sort();
                    for key in keys {
                        if let Some(val) = fields.get(key) {
                            out.push_str(&format!("{key} = {val}\n"));
                        }
                    }
                }
                Some(Value::Bool(false)) => {}
                _ => {}
            }
        }
    }

    out.push_str("\n[gate]\n");
    out.push_str("file = [\"critical\", \"high\"]\n");
    out.push_str("staged = [\"critical\", \"high\"]\n");
    out
}

/// Detected stack values used to author config.
#[derive(Debug, Clone)]
pub struct DetectedConfig {
    pub roots: Vec<String>,
    pub exts: Vec<String>,
    pub skip_dirs: Vec<String>,
    pub checkers: Value,
}

fn ensure_hook_entry(
    settings: &mut Value,
    event: &str,
    matcher: Option<&str>,
    command: &str,
) -> bool {
    let hooks = settings.as_object_mut().and_then(|o| {
        o.entry("hooks".to_string())
            .or_insert_with(|| json!({}))
            .as_object_mut()
    });
    let Some(hooks) = hooks else {
        return false;
    };

    let event_arr = hooks.entry(event.to_string()).or_insert_with(|| json!([]));
    let Some(entries) = event_arr.as_array_mut() else {
        return false;
    };

    if matcher.is_none() {
        let present = entries.iter().any(|e| {
            e.get("hooks")
                .and_then(|h| h.as_array())
                .is_some_and(|arr| {
                    arr.iter().any(|h| {
                        h.get("type") == Some(&json!("command"))
                            && h.get("command") == Some(&json!(command))
                    })
                })
        });
        if present {
            return false;
        }
        entries.push(json!({ "hooks": [{ "type": "command", "command": command }] }));
        return true;
    }

    let matcher = matcher.unwrap();
    let entry = if let Some(idx) = entries
        .iter()
        .position(|e| e.get("matcher") == Some(&json!(matcher)))
    {
        &mut entries[idx]
    } else {
        entries.push(json!({ "matcher": matcher, "hooks": [] }));
        entries.last_mut().unwrap()
    };

    if entry.get("hooks").and_then(|h| h.as_array()).is_none() {
        entry["hooks"] = json!([]);
    }
    let hooks_arr = entry["hooks"].as_array_mut().unwrap();
    let present = hooks_arr.iter().any(|h| {
        h.get("type") == Some(&json!("command")) && h.get("command") == Some(&json!(command))
    });
    if present {
        return false;
    }
    hooks_arr.push(json!({ "type": "command", "command": command }));
    true
}

/// Idempotently merge slopgate hooks into a claude-format hooks JSON file.
pub fn merge_agent_hooks_file(
    file_path: &Path,
    engine_root: &Path,
) -> Result<(String, PathBuf), SlopError> {
    crate::install::agent_hooks::merge_hooks(file_path, engine_root)
        .map(|r| (r.action.to_string(), r.path))
}

/// Merge slopgate agent hooks into `.claude/settings.json`.
pub fn merge_settings_json(
    target_dir: &Path,
    engine_root: &Path,
    stderr: &mut dyn Write,
) -> Result<SettingsAction, SlopError> {
    let (commit, edit, session) = {
        let (commit, edit, session) = hook_paths(engine_root);
        (commit, edit, session)
    };
    let claude_dir = target_dir.join(".claude");
    let settings_path = claude_dir.join("settings.json");
    fs::create_dir_all(&claude_dir)
        .map_err(|e| SlopError::Io(format!("mkdir {}: {e}", claude_dir.display())))?;

    if !settings_path.is_file() {
        let settings = json!({
            "hooks": {
                "PreToolUse": [{
                    "matcher": "Bash",
                    "hooks": [{ "type": "command", "command": commit }]
                }],
                "PostToolUse": [{
                    "matcher": "Edit|Write",
                    "hooks": [{ "type": "command", "command": edit }]
                }],
                "SessionStart": [{
                    "hooks": [{ "type": "command", "command": session }]
                }],
            }
        });
        fs::write(
            &settings_path,
            format!(
                "{}\n",
                serde_json::to_string_pretty(&settings).map_err(|e| {
                    SlopError::Parse(format!("serialize {}: {e}", settings_path.display()))
                })?
            ),
        )
        .map_err(|e| SlopError::Io(format!("write {}: {e}", settings_path.display())))?;
        return Ok(SettingsAction::Created);
    }

    let raw = fs::read_to_string(&settings_path)
        .map_err(|e| SlopError::Io(format!("read {}: {e}", settings_path.display())))?;
    let mut settings: Value = match serde_json::from_str(&raw) {
        Ok(v) => v,
        Err(_) => {
            let _ = writeln!(
                stderr,
                "slopgate: {} is not valid JSON — left untouched; add hooks manually",
                settings_path.display()
            );
            return Ok(SettingsAction::InvalidJson);
        }
    };

    if !settings.is_object() {
        settings = json!({});
    }

    let added_pre = ensure_hook_entry(&mut settings, "PreToolUse", Some("Bash"), &commit);
    let added_post = ensure_hook_entry(&mut settings, "PostToolUse", Some("Edit|Write"), &edit);
    let added_session = ensure_hook_entry(&mut settings, "SessionStart", None, &session);

    if !added_pre && !added_post && !added_session {
        return Ok(SettingsAction::AlreadyPresent);
    }

    let bak = format!("{}.bak", settings_path.display());
    fs::copy(&settings_path, &bak)
        .map_err(|e| SlopError::Io(format!("copy {} -> {bak}: {e}", settings_path.display())))?;
    fs::write(
        &settings_path,
        format!(
            "{}\n",
            serde_json::to_string_pretty(&settings).map_err(|e| {
                SlopError::Parse(format!("serialize {}: {e}", settings_path.display()))
            })?
        ),
    )
    .map_err(|e| SlopError::Io(format!("write {}: {e}", settings_path.display())))?;
    Ok(SettingsAction::Merged)
}

pub fn format_suppressions_json() -> String {
    format!(
        "{}\n",
        serde_json::to_string_pretty(&json!({ "version": 1, "entries": [] })).unwrap()
    )
}

pub fn convention_sources_json(sources: &crate::init::detect_stack::ConventionSources) -> String {
    format!(
        "{}\n",
        serde_json::to_string_pretty(&json!({
            "version": sources.version,
            "generated_hint": sources.generated_hint,
            "claude_md": sources.claude_md,
            "skills": sources.skills,
            "agents": sources.agents,
            "commands": sources.commands,
            "editor_rules": sources.editor_rules,
            "knowledge_docs": sources.knowledge_docs,
        }))
        .unwrap()
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use tempfile::TempDir;

    #[test]
    fn format_config_toml_matches_fixture_shape() {
        let toml = format_config_toml(&DetectedConfig {
            roots: vec!["src".to_string()],
            exts: vec![".ts".to_string(), ".tsx".to_string(), ".astro".to_string()],
            skip_dirs: vec![
                "node_modules".to_string(),
                "dist".to_string(),
                "tests".to_string(),
                ".worktrees".to_string(),
            ],
            checkers: json!({ "diff-shape": { "maxDirs": 5 } }),
        });
        assert!(toml.contains("roots = [\"src\"]"));
        assert!(toml.contains("skipDirs = "));
        assert!(toml.contains("[checkers.diff-shape]"));
        assert!(toml.contains("maxDirs = 5"));
        assert!(toml.contains("[gate]"));
    }

    #[test]
    fn merge_settings_json_creates_fresh_file() {
        let dir = TempDir::new().unwrap();
        let engine = dir.path().join("engine");
        fs::create_dir_all(engine.join("hooks")).unwrap();
        fs::write(engine.join("hooks/commit-hook.sh"), "").unwrap();
        fs::write(engine.join("hooks/edit-hook.sh"), "").unwrap();
        fs::write(engine.join("hooks/session-start.sh"), "").unwrap();

        let mut stderr = Vec::new();
        let action = merge_settings_json(dir.path(), &engine, &mut stderr).unwrap();
        assert_eq!(action, SettingsAction::Created);
        assert!(dir.path().join(".claude/settings.json").is_file());
    }

    #[test]
    fn merge_settings_json_invalid_json_left_untouched() {
        let dir = TempDir::new().unwrap();
        let engine = dir.path().join("engine");
        fs::create_dir_all(engine.join("hooks")).unwrap();
        fs::write(engine.join("hooks/commit-hook.sh"), "").unwrap();
        fs::write(engine.join("hooks/edit-hook.sh"), "").unwrap();
        fs::write(engine.join("hooks/session-start.sh"), "").unwrap();
        fs::create_dir_all(dir.path().join(".claude")).unwrap();
        fs::write(dir.path().join(".claude/settings.json"), "{ not json").unwrap();

        let mut stderr = Vec::new();
        let action = merge_settings_json(dir.path(), &engine, &mut stderr).unwrap();
        assert_eq!(action, SettingsAction::InvalidJson);
        let msg = String::from_utf8(stderr).unwrap();
        assert!(msg.contains("not valid JSON"));
        assert_eq!(
            fs::read_to_string(dir.path().join(".claude/settings.json")).unwrap(),
            "{ not json"
        );
    }
}
