//! Init scaffold helpers — port of `src/init/scaffold.mjs`.

use crate::error::SlopError;
use serde_json::{json, Value};
use std::io::Write;
use std::path::{Path, PathBuf};

pub const DEPCRUISE_STARTER: &str = r"// generated by slopgate init — universal rules; add project layer rules here.
module.exports = {
  forbidden: [
    { name: 'no-circular', severity: 'error', from: {}, to: { circular: true } },
    { name: 'no-orphans', severity: 'warn', from: { orphan: true, pathNot: ['\\.d\\.ts$'] }, to: {} },
  ],
  options: { doNotFollow: { path: 'node_modules' }, tsPreCompilationDeps: true },
};
";

/// What happened to the project `.claude/settings.json` during init.
///
/// Init does NOT write project-level slopgate agent hooks (see
/// [`merge_settings_json`]); it only prunes any a prior version left behind.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SettingsAction {
    /// Stale slopgate hook entries were found and removed.
    Pruned,
    /// File exists, carried no slopgate hooks — left untouched.
    NotPresent,
    /// No `.claude/settings.json` — nothing to do (the common, correct case).
    Absent,
    /// File is not valid JSON — left untouched.
    InvalidJson,
}

impl SettingsAction {
    pub fn as_str(self) -> &'static str {
        match self {
            SettingsAction::Pruned => "pruned stale slopgate hooks",
            SettingsAction::NotPresent => "no slopgate hooks (untouched)",
            SettingsAction::Absent => "not written (global hooks enforce)",
            SettingsAction::InvalidJson => "invalid-json (untouched)",
        }
    }
}

fn json_array(values: &[String]) -> String {
    let inner: Vec<String> = values
        .iter()
        .map(|v| format!("\"{}\"", v.replace('\\', "\\\\").replace('"', "\\\"")))
        .collect();
    format!("[{}]", inner.join(", "))
}

/// Format native `.slopgate/config.toml` — 1:1 fields with JS `formatConfig` output.
pub fn format_config_toml(detected: &DetectedConfig) -> String {
    let mut out = String::new();
    out.push_str(&format!("roots = {}\n", json_array(&detected.roots)));
    out.push_str(&format!("exts = {}\n", json_array(&detected.exts)));
    out.push_str(&format!("skipDirs = {}\n", json_array(&detected.skip_dirs)));
    out.push_str("baseline = [\"no-stubs\", \"ts-suppress\", \"as-any\"]\n");
    out.push_str("rules = []\n");
    out.push_str("astRules = \"./rules/ast\"\n");
    out.push_str("astDisable = []\n");
    out.push_str("suppressions = \"./suppressions.json\"\n");
    out.push_str("fixtures = \"./fixtures\"\n");

    if let Value::Object(checkers) = &detected.checkers {
        let mut names: Vec<&String> = checkers.keys().collect();
        names.sort();
        for name in names {
            match checkers.get(name) {
                Some(Value::Bool(true)) => {
                    out.push_str(&format!("\n[checkers.{name}]\n"));
                }
                Some(Value::Object(fields)) => {
                    out.push_str(&format!("\n[checkers.{name}]\n"));
                    let mut keys: Vec<&String> = fields.keys().collect();
                    keys.sort();
                    for key in keys {
                        if let Some(val) = fields.get(key) {
                            out.push_str(&format!("{key} = {val}\n"));
                        }
                    }
                }
                Some(Value::Bool(false)) => {}
                _ => {}
            }
        }
    }

    out.push_str("\n[gate]\n");
    out.push_str("file = [\"critical\", \"high\"]\n");
    out.push_str("staged = [\"critical\", \"high\"]\n");
    out
}

/// Detected stack values used to author config.
#[derive(Debug, Clone)]
pub struct DetectedConfig {
    pub roots: Vec<String>,
    pub exts: Vec<String>,
    pub skip_dirs: Vec<String>,
    pub checkers: Value,
}

/// Idempotently merge slopgate hooks into a claude-format hooks JSON file.
pub fn merge_agent_hooks_file(
    file_path: &Path,
    engine_root: &Path,
) -> Result<(String, PathBuf), SlopError> {
    crate::install::agent_hooks::merge_hooks(file_path, engine_root)
        .map(|r| (r.action.to_string(), r.path))
}

/// Prune any slopgate agent hooks from the PROJECT `.claude/settings.json`.
///
/// Init deliberately does NOT write project-level slopgate agent hooks. They are
/// redundant with the per-user global agent hooks (installed by
/// `install_agent_hooks`, which self-gate on `.slopgate/config.toml`) and with
/// the native git pre-commit hook — and because every entry embeds an absolute
/// engine path, a project entry leaks the author's local install path into any
/// repo that *tracks* `.claude/settings.json`, breaking on every other machine
/// and stacking stale/duplicate entries on each init (the dedup-by-exact-path
/// weakness). So init self-heals: it removes any slopgate entry — matched by
/// script *identity*, so foreign-root and prior-version entries are caught too —
/// while preserving all non-slopgate hooks. Enforcement stays in the global
/// hooks plus the git hook.
pub fn merge_settings_json(
    target_dir: &Path,
    engine_root: &Path,
    stderr: &mut dyn Write,
) -> Result<SettingsAction, SlopError> {
    let settings_path = target_dir.join(".claude").join("settings.json");
    if !settings_path.is_file() {
        return Ok(SettingsAction::Absent);
    }

    let result = crate::install::agent_hooks::remove_hooks(&settings_path, engine_root)?;
    Ok(match result.action {
        "removed" => SettingsAction::Pruned,
        "invalid-json" => {
            let _ = writeln!(
                stderr,
                "slopgate: {} is not valid JSON — left untouched",
                settings_path.display()
            );
            SettingsAction::InvalidJson
        }
        // "not-found" | "not-present"
        _ => SettingsAction::NotPresent,
    })
}

pub fn format_suppressions_json() -> String {
    format!(
        "{}\n",
        serde_json::to_string_pretty(&json!({ "version": 1, "entries": [] })).unwrap()
    )
}

pub fn convention_sources_json(sources: &crate::init::detect_stack::ConventionSources) -> String {
    format!(
        "{}\n",
        serde_json::to_string_pretty(&json!({
            "version": sources.version,
            "generated_hint": sources.generated_hint,
            "claude_md": sources.claude_md,
            "skills": sources.skills,
            "agents": sources.agents,
            "commands": sources.commands,
            "editor_rules": sources.editor_rules,
            "knowledge_docs": sources.knowledge_docs,
        }))
        .unwrap()
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use serde_json::json;
    use tempfile::TempDir;

    #[test]
    fn format_config_toml_matches_fixture_shape() {
        let toml = format_config_toml(&DetectedConfig {
            roots: vec!["src".to_string()],
            exts: vec![".ts".to_string(), ".tsx".to_string(), ".astro".to_string()],
            skip_dirs: vec![
                "node_modules".to_string(),
                "dist".to_string(),
                "tests".to_string(),
                ".worktrees".to_string(),
            ],
            checkers: json!({ "diff-shape": { "maxDirs": 5 } }),
        });
        assert!(toml.contains("roots = [\"src\"]"));
        assert!(toml.contains("skipDirs = "));
        assert!(toml.contains("[checkers.diff-shape]"));
        assert!(toml.contains("maxDirs = 5"));
        assert!(toml.contains("[gate]"));
    }

    #[test]
    fn merge_settings_json_does_not_create_file() {
        // No project settings.json → init must NOT write project agent hooks.
        let dir = TempDir::new().unwrap();
        let engine = dir.path().join("engine");

        let mut stderr = Vec::new();
        let action = merge_settings_json(dir.path(), &engine, &mut stderr).unwrap();
        assert_eq!(action, SettingsAction::Absent);
        assert!(!dir.path().join(".claude/settings.json").exists());
    }

    #[test]
    fn merge_settings_json_invalid_json_left_untouched() {
        let dir = TempDir::new().unwrap();
        let engine = dir.path().join("engine");
        fs::create_dir_all(dir.path().join(".claude")).unwrap();
        fs::write(dir.path().join(".claude/settings.json"), "{ not json").unwrap();

        let mut stderr = Vec::new();
        let action = merge_settings_json(dir.path(), &engine, &mut stderr).unwrap();
        assert_eq!(action, SettingsAction::InvalidJson);
        let msg = String::from_utf8(stderr).unwrap();
        assert!(msg.contains("not valid JSON"));
        assert_eq!(
            fs::read_to_string(dir.path().join(".claude/settings.json")).unwrap(),
            "{ not json"
        );
    }

    #[test]
    fn merge_settings_json_prunes_stale_slopgate_hooks_keeps_foreign() {
        // A repo whose tracked .claude/settings.json carries a STALE slopgate
        // hook from a foreign install root (the /home/runner poison) plus an
        // unrelated project hook. Init must remove the slopgate entry by
        // identity and preserve the unrelated hook.
        let dir = TempDir::new().unwrap();
        let engine = dir.path().join("engine"); // current root — irrelevant to the stale path
        fs::create_dir_all(dir.path().join(".claude")).unwrap();
        let poisoned = r#"{
  "hooks": {
    "PreToolUse": [
      { "matcher": "Bash", "hooks": [
        { "type": "command", "command": "/home/runner/work/slopgate/slopgate/hooks/commit-hook.sh" },
        { "type": "command", "command": "apps/web/scripts/code-quality/edit-hook.sh" }
      ] }
    ],
    "SessionStart": [
      { "hooks": [ { "type": "command", "command": "/foreign/root/hooks/session-start.sh" } ] }
    ]
  }
}"#;
        fs::write(dir.path().join(".claude/settings.json"), poisoned).unwrap();

        let mut stderr = Vec::new();
        let action = merge_settings_json(dir.path(), &engine, &mut stderr).unwrap();
        assert_eq!(action, SettingsAction::Pruned);

        let after = fs::read_to_string(dir.path().join(".claude/settings.json")).unwrap();
        // Stale slopgate hooks gone (foreign roots matched by identity).
        assert!(!after.contains("commit-hook.sh"));
        assert!(!after.contains("session-start.sh"));
        // Non-slopgate project hook preserved — its suffix is NOT a slopgate suffix.
        assert!(after.contains("code-quality/edit-hook.sh"));
    }
}
