import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
export const BASELINE_AST_DIR = join(__dirname, 'ast');
export const BASELINE_FIXTURES_DIR = join(__dirname, 'fixtures');

/** @type {Record<string, import('../../src/config.mjs').Pattern[]>} */
export const BASELINE_PACKS = {
  'no-stubs': [{
    id: 'no-stubs-placeholder', title: 'Stub / placeholder / not-implemented marker',
    category: 'convention', severity: 'critical',
    pattern: '(?:for now|in a real app|placeholder\\s+(?:for now|implementation|impl|until)\\b|TODO: ?implement|not implemented)',
    flags: 'i',
    description: 'Stub or deferred-work marker — global rule forbids stubs/placeholders/workarounds.',
    resolution: 'Implement the real behavior now; remove the placeholder.',
    canary: '// placeholder for now',
    negativeCanary: [
      "placeholder={t('x')}",
      'placeholder:text-ink',
      'admin.incidents.titlePlaceholder',
      'const namePlaceholder = 1',
    ],
  }],
  'ts-suppress': [{
    id: 'ts-suppress-added', title: 'TypeScript suppression directive',
    category: 'convention', severity: 'high',
    pattern: '(?:\\/\\/\\s*|\\/\\*\\s*)?@ts-(?:ignore|expect-error|nocheck)\\b',
    description: 'Suppressing the type checker instead of fixing the cause.',
    resolution: 'Fix the underlying type error; remove the suppression.',
    canary: '// @ts-expect-error',
    negativeCanary: ['/* eslint-disable zync/no-raw-html-in-pages */'],
  }],
  'as-any': [{
    id: 'as-any-cast', title: '`as any` cast',
    category: 'convention', severity: 'high',
    pattern: 'as any\\b',
    description: 'Escape-hatch cast that disables type safety.',
    resolution: 'Use a precise type or a discriminated narrowing.',
    canary: 'const x = foo as any;',
  }],
  'raw-hex': [{
    id: 'raw-hex-color', title: 'Hardcoded hex color',
    category: 'convention', severity: 'high',
    pattern: '#[0-9a-fA-F]{3,8}\\b',
    description: 'Raw hex color in source instead of a design token.',
    resolution: 'Use a CSS custom property / design token.',
    excludeGlobs: ['**/tokens.css', '**/tokens/**'],
    canary: 'color: #ff0044;',
  }, {
    id: 'raw-px-spacing', title: 'Magic px spacing instead of a design token',
    category: 'convention', severity: 'high',
    pattern: ':\\s*\\d{2,}px\\b',
    description: 'Hardcoded multi-digit px value in a style declaration — bypasses the spacing scale (ANTI-SLOP UX §15).',
    resolution: 'Use a spacing token / utility scale (var(--space-md), Tailwind p-4) instead of a raw px literal.',
    excludeGlobs: ['**/tokens.css', '**/tokens/**', '**/*.stories.*'],
    canary: 'margin-top: 17px;',
    negativeCanary: ['border: 1px solid;', 'padding: var(--space-4);', 'gap: 8px;'],
  }, {
    id: 'raw-rgb-color', title: 'Hardcoded rgb()/hsl() color',
    category: 'convention', severity: 'high',
    pattern: '\\b(?:rgba?|hsla?)\\((?![^)]*var\\()',
    description: 'Raw rgb()/hsl() color literal instead of a design token (ANTI-SLOP UX §15).',
    resolution: 'Use a CSS custom property / token; a token may itself wrap rgb(var(--…)).',
    excludeGlobs: ['**/tokens.css', '**/tokens/**', '**/*.stories.*'],
    canary: 'color: rgb(255, 0, 0);',
    negativeCanary: ['background: hsl(var(--hue), 50%, 50%);', 'const c = var(--ink);'],
  }],
  'kv-ban': [{
    id: 'kv-binding-usage', title: 'Cloudflare KV usage',
    category: 'boundary', severity: 'critical',
    pattern: '\\bKVNamespace\\b|env\\.[A-Z_]*KV\\b|env\\.KV\\b|KV_NAMESPACE',
    description: 'KV is eventually-consistent; banned for stateful/read-after-write paths.',
    resolution: 'Use a Durable Object (strong consistency) or cache.default (read caching).',
    canary: 'const store: KVNamespace = env.KV_STORE;',
  }],
  'live-secrets': [{
    id: 'live-secret-literal', title: 'Live secret literal in source',
    category: 'security', severity: 'critical',
    pattern: 'sk_live_[0-9a-zA-Z]{8,}|pk_live_[0-9a-zA-Z]{8,}|whsec_[0-9a-zA-Z]{8,}|AIza[0-9A-Za-z_-]{30,}',
    description: 'Stripe/webhook/Google API live credential hardcoded in source.',
    resolution: 'Move to a secret manager or environment variable; never commit live keys.',
    canary: 'const key = "sk_live_aaaaaaaaaaaa";',
  }],
  'eval-ban': [{
    id: 'eval-dynamic-code', title: 'Dynamic code evaluation (eval / new Function)',
    category: 'security', severity: 'critical',
    pattern: '\\beval\\(|\\bnew Function\\(',
    description: 'Dynamic code evaluation creates XSS/injection surface.',
    resolution: 'Eliminate eval(); use static dispatch tables or data-driven config.',
    excludeGlobs: ['**/tests/**', '**/scripts/**'],
    canary: 'eval(userCode);',
  }],
  'pii-logs': [{
    id: 'pii-in-logs', title: 'PII field in console.log',
    category: 'security', severity: 'high',
    pattern: 'console\\.log\\([^)]*\\.(phone|email|password|token|secret)',
    description: 'PII fields logged — may appear in log tails and error trackers.',
    resolution: 'Remove log or redact sensitive fields before logging.',
    excludeGlobs: ['**/tests/**', '**/scripts/**'],
    canary: 'console.log(user.phone, user.email);',
  }],
  'weak-hash': [{
    id: 'weak-hash-algorithm', title: 'Weak hash algorithm (MD5/SHA-1)',
    category: 'security', severity: 'high',
    pattern: "createHash\\('md5'\\)|createHash\\('sha1'\\)|createHash\\(\"md5\"\\)|createHash\\(\"sha1\"\\)",
    description: 'MD5/SHA-1 are cryptographically broken — forbidden for integrity checks and unusable for passwords.',
    resolution: 'Use SHA-256+ for integrity; bcrypt/argon2/scrypt for passwords.',
    canary: "createHash('md5').update(data).digest('hex')",
  }],
  'sql-safety': [{
    id: 'sql-for-update-aggregate',
    title: 'FOR UPDATE on aggregate query (SQL runtime error)',
    category: 'convention',
    severity: 'critical',
    flags: 'i',
    pattern: '\\b(SUM|COUNT|AVG|MAX|MIN)\\s*\\([^)]*\\).*\\bFOR\\s+UPDATE\\b|\\bFOR\\s+UPDATE\\b.*\\b(SUM|COUNT|AVG|MAX|MIN)\\s*\\(',
    description: 'SQL FOR UPDATE with an aggregate function (SUM/COUNT/etc.) — Postgres (and SQL standard) rejects this at runtime: "FOR UPDATE is not allowed with aggregate functions".',
    resolution: 'Remove FOR UPDATE from aggregate queries. Only use FOR UPDATE on plain row-locking SELECTs: SELECT ... FROM t WHERE id = $1 FOR UPDATE.',
    canary: 'const q = `SELECT SUM(amount) FROM ledger WHERE user_id = $1 FOR UPDATE`;',
    negativeCanary: [
      'const q = `SELECT id FROM users WHERE id = $1 FOR UPDATE`;',
      'const q = `SELECT SUM(amount) FROM ledger GROUP by user_id`;',
    ],
  }],
};