import {
  mkdirSync, writeFileSync, readFileSync, copyFileSync, existsSync,
} from 'node:fs';
import { join } from 'node:path';
import { ENGINE_ROOT } from '../install-hooks.mjs';

export const DEPCRUISE_STARTER = `// generated by slopgate init — universal rules; add project layer rules here.
module.exports = {
  forbidden: [
    { name: 'no-circular', severity: 'error', from: {}, to: { circular: true } },
    { name: 'no-orphans', severity: 'warn', from: { orphan: true, pathNot: ['\\\\.d\\\\.ts$'] }, to: {} },
  ],
  options: { doNotFollow: { path: 'node_modules' }, tsPreCompilationDeps: true },
};
`;

const COMMIT_HOOK = `${ENGINE_ROOT}/hooks/commit-hook.sh`;
const EDIT_HOOK = `${ENGINE_ROOT}/hooks/edit-hook.sh`;
const SESSION_HOOK = `${ENGINE_ROOT}/hooks/session-start.sh`;

const PRE_TOOL = { matcher: 'Bash', command: COMMIT_HOOK };
const POST_TOOL = { matcher: 'Edit|Write', command: EDIT_HOOK };

/** @param {{ roots: string[], exts: string[], skipDirs: string[], checkers: Record<string, any> }} detected */
export function formatConfig(detected) {
  const checkerLines = Object.entries(detected.checkers)
    .map(([k, v]) => `    '${k}': ${JSON.stringify(v)},`).join('\n');
  return `// generated by slopgate init — review roots + add project rule packs (see convention-sources.json).
// slopgate project config. Engine is global+auto-latest; THIS file is pinned per project.
export default {
  roots: ${JSON.stringify(detected.roots)},
  exts: ${JSON.stringify(detected.exts)},
  skipDirs: ${JSON.stringify(detected.skipDirs)},

  // baseline packs this project OPTS INTO (nothing fires until listed)
  baseline: ['no-stubs', 'ts-suppress', 'as-any'],

  // UX module — OPTIONAL, opt-in per sub-module. Opinionated UI-hygiene rules
  // from the ANTI-SLOP UX framework. Off by default (UX taste varies); these are
  // good-enough defaults for a new project with no strong opinion. Uncomment a
  // line to enable it; value = severity ('advisory' reports but never blocks a
  // commit, 'high' gates). Delete the whole block to opt out entirely.
  // ux: {
  //   a11y: 'high',      // §11 <div onClick>→<button>, semantic HTML (gates)
  //   cls:  'high',      // §13 <img> without width/height → layout shift (gates)
  //   taste: 'advisory', // §0/§6/§26 emoji-icon, "Trusted by", Lorem, linear easing (reports only)
  // },

  // project-owned rule packs (pinned, in this repo)
  rules: [],                      // e.g. ['./rules/my-rule.mjs']
  astRules: './rules/ast',        // dir of *.yml (optional)
  astDisable: [],                 // ast rule ids to silence in this project

  // commit-tier checkers (detected at init; false/absent = off)
  checkers: {
${checkerLines}
  },

  gate: { file: ['critical', 'high'], staged: ['critical', 'high'] },
  suppressions: './suppressions.json',
  fixtures: './fixtures',
};
`;
}

/**
 * @param {unknown} settings
 * @param {{ matcher: string, command: string }} spec
 */
function ensureHookEntry(settings, event, spec) {
  if (!settings.hooks) settings.hooks = {};
  if (!Array.isArray(settings.hooks[event])) settings.hooks[event] = [];

  if (spec.matcher === undefined) {
    const entries = settings.hooks[event];
    const present = entries.some((e) =>
      Array.isArray(e?.hooks) && e.hooks.some((h) => h?.type === 'command' && h?.command === spec.command),
    );
    if (present) return false;
    entries.push({ hooks: [{ type: 'command', command: spec.command }] });
    return true;
  }

  let entry = settings.hooks[event].find((e) => e?.matcher === spec.matcher);
  if (!entry) {
    entry = { matcher: spec.matcher, hooks: [] };
    settings.hooks[event].push(entry);
  }
  if (!Array.isArray(entry.hooks)) entry.hooks = [];

  const present = entry.hooks.some((h) => h?.type === 'command' && h?.command === spec.command);
  if (!present) entry.hooks.push({ type: 'command', command: spec.command });
  return !present;
}

/**
 * @param {string} targetDir
 * @returns {'created' | 'merged' | 'already-present' | 'invalid-json'}
 */
export function mergeSettingsJson(targetDir) {
  const claudeDir = join(targetDir, '.claude');
  const settingsPath = join(claudeDir, 'settings.json');
  mkdirSync(claudeDir, { recursive: true });

  if (!existsSync(settingsPath)) {
    const settings = {
      hooks: {
        PreToolUse: [{ matcher: PRE_TOOL.matcher, hooks: [{ type: 'command', command: PRE_TOOL.command }] }],
        PostToolUse: [{ matcher: POST_TOOL.matcher, hooks: [{ type: 'command', command: POST_TOOL.command }] }],
        SessionStart: [{ hooks: [{ type: 'command', command: SESSION_HOOK }] }],
      },
    };
    writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
    return 'created';
  }

  const raw = readFileSync(settingsPath, 'utf8');
  let settings;
  try { settings = JSON.parse(raw); }
  catch {
    process.stderr.write(`slopgate: ${settingsPath} is not valid JSON — left untouched; add hooks manually\n`);
    return 'invalid-json';
  }
  const addedPre = ensureHookEntry(settings, 'PreToolUse', PRE_TOOL);
  const addedPost = ensureHookEntry(settings, 'PostToolUse', POST_TOOL);
  const addedSession = ensureHookEntry(settings, 'SessionStart', { matcher: undefined, command: SESSION_HOOK });

  if (!addedPre && !addedPost && !addedSession) return 'already-present';

  copyFileSync(settingsPath, `${settingsPath}.bak`);
  writeFileSync(settingsPath, `${JSON.stringify(settings, null, 2)}\n`);
  return 'merged';
}
